-- MySQL Script generated by MySQL Workbench
-- Fri Jan 15 12:18:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema offdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `offdb` DEFAULT CHARACTER SET utf8 ;
USE `offdb` ;

-- -----------------------------------------------------
-- Table `offdb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `offdb`.`nutriscore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`nutriscore` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `offdb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `brand` VARCHAR(80) NULL DEFAULT NULL,
  `stores` VARCHAR(80) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `nutriscore_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  UNIQUE INDEX `product_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `offdb`.`substitutes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`substitutes` (
  `id` INT(11) NOT NULL,
  `substitute_id` INT(11) NOT NULL,
  `substituted_id` INT(11) NOT NULL,
  INDEX `substitute_id_idx` USING BTREE (`substitute_id`),
  INDEX `substituted_id_idx` (`substituted_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `substitute_id`
    FOREIGN KEY (`substitute_id`)
    REFERENCES `offdb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `substituted_id`
    FOREIGN KEY (`substituted_id`)
    REFERENCES `offdb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `offdb`.`categories_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offdb`.`categories_products` (
  `categories_id` INT(11) NOT NULL,
  `products_id` INT(11) NOT NULL,
  PRIMARY KEY (`categories_id`, `products_id`),
  INDEX `fk_categories_has_products_products1_idx` (`products_id` ASC),
  INDEX `fk_categories_has_products_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_categories_has_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `offdb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `offdb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;